name: flutter_clean_architecture
description: "A new Flutter project with clean architecture"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # Routing
  go_router: ^13.0.0

  # State Management (Recommended)
  flutter_riverpod: ^2.5.1 # Reactive state management

  # Network (Recommended)
  dio: ^5.4.1 # HTTP client
  retrofit: ^4.1.0 # Type-safe HTTP client
  json_annotation: ^4.8.1 # JSON serialization

  # Local Storage (Recommended)
  shared_preferences: ^2.2.2 # Key-value storage
  hive: ^2.2.3 # NoSQL database

  # Utils (Recommended)
  freezed_annotation: ^2.4.1 # Immutable classes
  dartz: ^0.10.1 # Functional programming
  logger: ^2.0.2 # Logging utility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generation (Recommended)
  build_runner: ^2.4.8
  freezed: ^2.4.7 # Code generation for immutable classes
  json_serializable: ^6.7.1 # JSON serialization
  retrofit_generator: ^8.1.0 # Retrofit code generation
  mockito: ^5.4.4 # Mocking for tests

flutter:
  uses-material-design: true
